name: cloud
description: Infrastructure-as-code for Open Web Services
runtime: go
config:
    docker:host:
        value: unix:///var/run/docker.sock
    pulumi:tags:
        value:
            pulumi:template: digitalocean-go
