name: cloud
description: Infrastructure-as-code for Open Web Services
runtime: go
config:
  pulumi:tags:
    value:
      pulumi:template: digitalocean-go
  docker:host:
    value: unix:///var/run/docker.sock
packages:
  netlify:
    source: terraform-provider
    version: 1.0.2
    parameters:
      - netlify/netlify

#     libvirt:uri:
#         value: qemu:///session?socket=/Users/mfarabi/.cache/libvirt/libvirt-sock

# packages:
#     libvirt:
#         source: terraform-provider
#         version: 1.0.2
#         parameters:
#             - dmacvicar/libvirt
